ci(pre-commit): Update version of commit-linter
Update of conventional-commi-linter because of not
 working with Python version 3.12.
UnicodeEncodeError: 'charmap' codec can't encode
character '\u274c' in position 2: character maps
to <undefined>