Fix black formatting with pre-commit
- Don't require a specific Python version for black because it might not be available
- Use a newer version of black where the following dependency issue has been fixed

ImportError: cannot import name '_unicodefun' from 'click' (/home/user/.cache/pre-commit/repo9r6ughsv/py_env-python3.10/lib/python3.10/site-packages/click/__init__.py)